name: Build & Release

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Electron App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Install Quasar CLI
        run: npm install -g @quasar/cli

      - name: Build Electron App
        run: npm run build:electron
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # 👈 Necesario para electron-builder publicar artefactos

      - name: Upload dist_electron
        uses: actions/upload-artifact@v4
        with:
          name: dist_electron
          path: dist_electron/

  release:
    name: Release with Semantic Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Download Electron artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist_electron
          path: dist_electron/

      - name: Fetch Git tags
        run: git fetch --tags

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # 👈 También puede requerirse aquí para publicar binarios
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
