name: Build & Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Electron
    runs-on: ubuntu-latest

    steps:
      # 1. Clona TODO el historial (necesario para tags y semantic-release)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2. Instala Node.js y cachea node_modules
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      # 3. Instala dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Compila tu app Electron + Quasar
      - name: Build Electron
        run: npm run build:electron

      # 5. Sube los instaladores como artefactos temporales
      - name: Upload dist_electron
        uses: actions/upload-artifact@v3
        with:
          name: dist_electron
          path: dist_electron/

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1. Vuelve a clonar (necesario para los commits, tags y changelog)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2. Descarga los binarios generados en el job build
      - name: Download dist_electron
        uses: actions/download-artifact@v3
        with:
          name: dist_electron
          path: dist_electron/

      # 3. Instala Node.js y cachea
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      # 4. Instala dependencias (incluye devDependencies con npm ci)
      - name: Install dependencies
        run: npm ci

      # 5. Lanza semantic-release
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # para @semantic-release/github y @semantic-release/git
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}         # si publicas además a npm
        run: npx semantic-release
